# Generated by Django 3.2.8 on 2021-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='Owner',
        ),
    ]
