# Generated by Django 3.2.8 on 2021-11-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0002_auto_20211106_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
    ]
